name: to_do_done
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
    #infinite carousel
  infinite_carousel: ^1.1.1
  #dio
  dio: ^5.4.1
  cupertino_icons: ^1.0.6
  http: ^1.2.1
  sqflite: ^2.0.0+3
  path_provider: ^2.0.2
  path: ^1.8.0
  shared_preferences: ^2.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  assets:
  - assets/jpg/
  - assets/png/
    